#
# Module manifest for module 'CoaOnlineModule'
#
# Generated by: joseph.crockett@alexandriava.gov
#
# Generated on: 3/17/2018
#

@{
    # Script module or binary module file associated with this manifest
    ModuleToProcess      = '.\CoaOnlineModule.psm1'

    # Script module or binary module file associated with this manifest
    #RootModule = ''

    # Version number of this module.
    ModuleVersion        = '1.0'

    # ID used to uniquely identify this module
    GUID                 = '1889cf05-1f5c-40dc-83dd-1bfcd22d13f8'

    # Author of this module
    Author               = 'joseph.crockett@alexandriava.gov'

    # Company or vendor of this module
    CompanyName          = 'City of Alexandria, Virginia'

    # Copyright statement for this module
    Copyright            = '(c) 2018 City of Alexandria, VA'

    # Description of the functionality provided by this module
    Description          = 'Loads scripts specific to COA business needs, specifically new hires and terminations in Office 365'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules   = ''

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # FunctionsToExport = ''

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.

    CmdletsToExport      = @("Set-CoaMailboxConfiguration", "Set-CoaExchangeAttributes", "Set-CoaExoAttributes", "New-CoaUser", "Get-CoaVariables", "Set-CoaVariables", "Clear-CoaUser", "Remove-CoaUser")

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "Scripting Techniques"
            
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('O365', 'MSOL', 'License', 'Management', 'SKU', 'Plan', 'AzueAD', 'Bulk')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/jcrocke9/CoaOnlineModule'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = '1.0.1 Initial Release'

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = 'Coa'
}
