#
# Module manifest for module 'CoaOnlineModule'
#
# Generated by: joseph.crockett@alexandriava.gov
#
# Generated on: 3/17/2018
#

@{

    # Script module or binary module file associated with this manifest
    #RootModule = ''
    
    # Version number of this module.
    ModuleVersion     = '1.0'
    
    # ID used to uniquely identify this module
    GUID              = '1889cf05-1f5c-40dc-83dd-1bfcd22d13f8'
    
    # Author of this module
    Author            = 'joseph.crockett@alexandriava.gov'
    
    # Company or vendor of this module
    CompanyName       = 'City of Alexandria, Virginia'
    
    # Copyright statement for this module
    Copyright         = '(c) 2018 City of Alexandria, VA'
    
    # Description of the functionality provided by this module
    Description       = 'Loads scripts specific to COA business needs, specifically new hires and terminations in Office 365'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(CoaLoggingModule)
}